services:
  caching-server:
    image: memcached:alpine
    container_name: memcached-server
    networks:
     - ipgeolocation_network
    restart: always
  ipgeolocator-app:
      build:
        dockerfile: ./Dockerfile
      environment:
        - HOSTNAME=api_app
        - MEMCACHED_HOST=caching-server
        - MEMCACHED_PORT=11211
        - API_KEY_FROM_SECRETSMANAGER=True
        - APP_PORT=8080
        - SECRET_KEY=API_KEY
        - SECRET_NAME=ipgeolocation_secret
        - REGION_NAME=us-east-1

      networks:
        - ipgeolocation_network
    
      depends_on:
        - caching-server
  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      environment:
        - HOSTNAME=frontend
        - API_SERVER=ipgeolocator-app
        - API_SERVER_PORT=8080
        - APP_PORT=80
      ports:
        - "80:80"

      networks:
        - ipgeolocation_network
    
      depends_on:
        - ipgeolocator-app
networks:
  ipgeolocation_network:
    driver: bridge

